server:
  port: 7000
spring:
  application:
    name: user-center
  datasource:
    druid:
      url: jdbc:mysql://${txlc.datasource.ip}:3306/user-center?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: ${txlc.datasource.username}
      password: ${txlc.datasource.password}
      driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.txlc.common.model
  global-config:
    db-config:
      id-type: auto

txlc:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.txlc.user.ctrl